# Generated by Django 4.0.3 on 2023-04-13 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classes', models.PositiveSmallIntegerField(default=0)),
                ('class_price', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('from_age', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('has_to_pay', models.PositiveSmallIntegerField(default=0)),
                ('paid', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveSmallIntegerField(default=0)),
                ('should_pay', models.BooleanField(default=True)),
                ('level', models.TextField(choices=[('N', 'Normal'), ('I', 'Intermediate'), ('A', 'Advanced')], default='N', max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_mark', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('A', 'Any'), ('E', 'Ease'), ('M', 'Middle'), ('H', 'Hard')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('takers', models.ManyToManyField(to='core.student')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
