# Generated by Django 4.0.3 on 2023-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='takers',
            field=models.ManyToManyField(to='core.group'),
        ),
    ]
