# Generated by Django 4.0.3 on 2023-04-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_test_takers'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
